export const DOMstring = {
    inputType: '.add__type',
    inputDescription: '.input__description',
    inputValue: '.input__value',
    formLabel: '.transction-form',
    incomesContainer: '.inc__list',
    expensesContainer: '.exp__list',
    budgetLabel: '.budget__value',
    incomeLabel: '.budget__income--value',
    expenseLabel: '.budget__expenses--value',
    percentageLabel: '.budget__expenses--percentage',
    container: '.history_list',
    itemPercLabel: '.item__percentage',
    dateLabel: '.item-time',
    decimalAmount: '.decimal-amount',
    deleteItemLabel: '.item__delete--btn',
    incTypeLabel: '.inc_check',
    expTypeLabel: '.exp_check',
    submitBTN: '.submit_btn',
    updateItemBtn: '.update_trans--feild',
    updateForm: '.update__value-form',
    updateInpDesc: '.update__description',
    updateInpValue: '.update__value',
    overlay: '.overlay',
    windowBox: '.update--window'
};